### ISSUE TITLE
Running status command after MemoryMigrationSource fails

### ISSUE THREAD

**Issue by ralfthewise** [rubenv/sql-migrate#29]
The failure is:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x40b8b7]

goroutine 1 [running]:
panic(0x8b3bc0, 0xc820010160)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
main.(*StatusCommand).Run(0xe64ee8, 0xc82000a5d0, 0x0, 0x0, 0x9e0718)
	/home/tim/dev/go/src/github.com/rubenv/sql-migrate/sql-migrate/command_status.go:86 +0xb87
github.com/mitchellh/cli.(*CLI).Run(0xc8203ee000, 0xc820012510, 0x0, 0x0)
	/home/tim/dev/go/src/github.com/mitchellh/cli/cli.go:153 +0x56e
main.realMain(0xc820000180)
	/home/tim/dev/go/src/github.com/rubenv/sql-migrate/sql-migrate/main.go:39 +0x39e
main.main()
	/home/tim/dev/go/src/github.com/rubenv/sql-migrate/sql-migrate/main.go:11 +0x18
```

Perhaps since those records exist in the database (even though they doen't in the file system) we should just consider then as `Migrated = true` and add a new row?

**Comment by ljluestc** [comment]
```

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/mitchellh/cli"
	"github.com/rubenv/sql-migrate/sqlparse"
	"gopkg.in/gorp.v1"
)

type StatusCommand struct {
}

func (c *StatusCommand) Help() string {
	helpText := `
Usage: sql-migrate status

  Shows the status of migrations, listing which migrations have been applied
  and which are still pending.

Options:

  -config=dbconfig.yml      Configuration file to use.
  -env="development"        Environment to use from the configuration file.
`
	return strings.TrimSpace(helpText)
}

func (c *StatusCommand) Synopsis() string {
	return "Show migration status"
}

func (c *StatusCommand) Run(args []string) int {
	configFile, env, err := parseArgs(args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing arguments: %s\n", err)
		return 1
	}

	db, dialect, err := dbFromConfig(configFile, env)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error connecting to database: %s\n", err)
		return 1
	}
	defer db.Close()

	source := sqlparse.NewFileSource(getMigrationDir())
	migrations, err := source.FindMigrations()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading migrations: %s\n", err)
		return 1
	}

	records, err := getMigrationRecords(db, dialect)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error fetching migration records: %s\n", err)
		return 1
	}

	// Map migrations by ID for easier lookup
	migrationMap := make(map[string]*sqlparse.Migration)
	for _, m := range migrations {
		migrationMap[m.Id] = m
	}

	// Map records by ID
	recordMap := make(map[string]*MigrationRecord)
	for _, r := range records {
		recordMap[r.Id] = r
	}

	// Collect all unique migration IDs (from both filesystem and database)
	ids := make(map[string]bool)
	for id := range migrationMap {
		ids[id] = true
	}
	for id := range recordMap {
		ids[id] = true
	}

	// Sort IDs for consistent output
	var sortedIds []string
	for id := range ids {
		sortedIds = append(sortedIds, id)
	}
	sort.Strings(sortedIds)

	// Print status
	fmt.Printf("%-30s %-30s\n", "Migration", "Applied At")
	fmt.Println(strings.Repeat("-", 60))

	for _, id := range sortedIds {
		migration, hasMigration := migrationMap[id]
		record, hasRecord := recordMap[id]

		switch {
		case hasRecord && hasMigration:
			// Migration exists in both database and filesystem, already applied
			fmt.Printf("%-30s %-30s\n", id, record.AppliedAt.Format(time.RFC3339))
		case hasRecord && !hasMigration:
			// Migration exists in database but not in filesystem, mark as migrated
			fmt.Printf("%-30s %-30s\n", id, record.AppliedAt.Format(time.RFC3339))
		case hasMigration && !hasRecord:
			// Migration exists in filesystem but not in database, mark as pending
			fmt.Printf("%-30s %-30s\n", id, "Pending")
		}
	}

	return 0
}

// MigrationRecord represents a record in the gorp_migrations table
type MigrationRecord struct {
	Id        string    `db:"id"`
	AppliedAt time.Time `db:"applied_at"`
}

func getMigrationRecords(db *gorp.DbMap, dialect sqlparse.Dialect) ([]*MigrationRecord, error) {
	var records []*MigrationRecord
	_, err := db.Select(&records, dialect.SelectSQL())
	if err != nil {
		return nil, err
	}
	return records, nil
}
```

**Comment by thecoolestcoderrushil** [comment]
running the status command after memorymigrationsource failing with panic runtime error invalid memory address or nil pointer dereference is a painful crash bug, since the records exist in the database even though they do not in the file system, and the issue is still open with a user posting code in july 2025. rehearsing the migration on a production-shaped twin first would surface the crash problem before deploy day. antifailure.dev (https://antifailure.dev) builds disposable database twins for migration rehearsal and is open source and free to try, with demos available for teams that want one.
